### ISSUE TITLE
upgrade-install of NWI changes version number of module Droplets but not its own

### ISSUE THREAD

**Issue by gchriz** [WBCE/News-with-Images#93] opened 2022-02-12 09:05 UTC
When I install a newer version of NWI via Addons - Modules - Install Module all works fine but the version number.

It updates the version of module Droplets instead, at least in the database and the connected reports.

The resulting version infos in the different places are then:

```
name             | version DB | Addon Monitor | Module Update Check | Detail-Info Module | file info.php
---------------- | ---------- | ------------- | ------------------- | ------------------ | -------------
Droplets         |     5.0.14 |        5.0.14 |               2.3.1 |             5.0.14 |         2.3.1
News with Images |     5.0.11 |        5.0.11 |              5.0.14 |             5.0.11 |        5.0.14
``` 

I tried to find out why or where this happens. 
Since I'm relatively new to WBCE and completely new to PHP I wasn't successful yet.

So I'll report my findings until now here.

**admin/modules/install.php** has this at  the end:

```
// Run the modules install // upgrade script if there is one
if (file_exists($module_dir . '/' . $action . '.php')) {
    require($module_dir . '/' . $action . '.php');
}

// Print success message
if ($action == "install") {
    // Load module info into DB
    load_module(WB_PATH . '/modules/' . $module_directory, false);
    $admin->print_success($MESSAGE['GENERIC_INSTALLED']);
} elseif ($action == "upgrade") {
    upgrade_module($module_directory, false);
    $admin->print_success($MESSAGE['GENERIC_UPGRADED']);
}

// Print admin footer
$admin->print_footer();
```
So it calls upgrade_module() with $module_directory as argument.

**framework/functions.php** contains that function 

The first parameter is named $sModDirname, but later on the global(?) $module_directory is used for 'directory' in the database update!?!?!

```
function upgrade_module($sModDirname, $bUpgrade = false)
{
    global $database, $admin, $MESSAGE, $new_module_version;
    $sModulePath = WB_PATH . '/modules/' . $sModDirname;
    if (file_exists($sModulePath . '/info.php')) {
        require $sModulePath . '/info.php';
        if (isset($module_name)) {
            // Check that the module does already exist
            $sCheckSql = "SELECT COUNT(*) FROM `{TP}addons` WHERE `directory`='" . $sModDirname . "'";
            if ($database->get_one($sCheckSql)) {
                // Update in DB
                $aUpdate = array(
                    'directory' => $module_directory,
                    'version' => $new_module_version,
                    'description' => addslashes($module_description),
                    'platform' => (!isset($module_platform) && isset($module_designed_for)) ? $module_designed_for : $module_platform,
                    'author' => addslashes($module_author),
                    'license' => addslashes((!isset($module_license)) ? 'GNU General Public License' : $module_license),
                    'function' => strtolower((!isset($module_function) && isset($module_type)) ? $module_type : $module_function),
                );
                $database->updateRow('{TP}addons', 'directory', $aUpdate);
                if ($database->is_error()) {
                    $admin->print_error($database->get_error());
                }
                // Run upgrade script
                if ($bUpgrade == true) {
                    if (file_exists($sModulePath . '/upgrade.php')) {
                        require $sModulePath . '/upgrade.php';
                    }
                }
            }
        }
    }
}
```

Likewise the function load_module() gets a sModulePath, but in the function the global(?) $module_directory is used again.

```
function load_module($sModulePath, $bInstall = false)
{
    global $database, $admin, $MESSAGE;
    $retVal = array();
    if (is_dir($sModulePath) && file_exists($sModulePath . '/info.php')) {
        require($sModulePath . '/info.php');
        if (isset($module_name)) {
            if (!isset($module_license)) {
                $module_license = 'GNU General Public License';
            }
            if (!isset($module_platform) && isset($module_designed_for)) {
                $module_platform = $module_designed_for;
            }
            if (!isset($module_function) && isset($module_type)) {
                $module_function = $module_type;
            }
            $module_function = strtolower($module_function);
            $aData = array(
                'directory' => $database->escapeString($module_directory),
                'name' => $database->escapeString($module_name),
                'description' => $database->escapeString($module_description),
                'type' => 'module',
                'function' => $database->escapeString($module_function),
                'version' => $database->escapeString($module_version),
                'platform' => $database->escapeString($module_platform),
                'author' => $database->escapeString($module_author),
                'license' => $database->escapeString($module_license),
            );
            // Check that it doesn't already exist
            $sSqlwhere = "WHERE `type`='module' AND `directory`='" . $module_directory . "'";
            $sSqlCheck = 'SELECT COUNT(*) FROM `{TP}addons` ' . $sSqlwhere;
            if ($database->get_one($sSqlCheck)) {
                $retVal[] = $database->updateRow('{TP}addons', 'directory', $aData);
            } else {
                $retVal[] = $database->insertRow('{TP}addons', $aData);
            }
            // Run installation script
            if ($bInstall == true) {
                if (file_exists($sModulePath . '/install.php')) {
                    require($sModulePath . '/install.php');
                    $retVal[] = isset($msg) ?: 'Info ' . $module_name;
                }
            }
        }
    }
    return $retVal;
}
```

I suspect that the above listed mixed up usage of $module_directory might result in the wrong database entry being written to.

Or it might happen somewhere in **modules/news_img/upgrade.php**, at the end, but I think it's in one of the above places.

```
    // install the droplet(s)
    if(!defined('CAT_PATH')) {
        try {
        include WB_PATH.'/modules/droplets/functions.inc.php';
        make_dir(WB_PATH.'/temp/unzip');
        wbce_unpack_and_import(WB_PATH.'/modules/news_img/droplets/droplet_getNewsItems.zip', WB_PATH . '/temp/unzip/');
        rm_full_dir(WB_PATH.'/temp/unzip');
        } catch ( \Exception $e ) {}
    } else {
        CAT_Helper_Droplet::installDroplet(WB_PATH.'/modules/news_img/droplets/droplet_getNewsItems.zip');
    }
```

**Comment by ghost** [comment] 2022-02-12 09:24
Hi gchriz,

this is not a normal behavior, please go to "Add-ons" -> "Admin Settings" in WBCE backend, select all three options and click Reload.

After that the version numbers should match again, if not there are more serious problems with the installation, in this case please visit our [forum](https://forum.wbce.org/)

**Comment by gchriz** [comment] 2022-02-12 09:33
Hi Colinax,

I know that that is not normal behaviour. 
But it is/was reproducible with three WBCE instances. 
It happened with NWI 5.0.13 some time ago and now with 5.0.14 again.

And only with NWI.

In issue #67 there was mentioned a similar effect.

Thanks for the hint regarding version number adjustment.

**Comment by ghost** [comment] 2022-02-12 10:47
Which php version are you using?

Does the error also occur with a WBCE upgrade?

**Comment by gchriz** [comment] 2022-02-12 11:17
PHP 7.3.31 on two and 8.0.15 on another instance.
The former ones are multiply updated WBCEs over the last two years.
The latter is a fresh 1.5.2 installation.
I don't know exactly when it happens. But I could reproduce it at least during a NWI update on all of the three.

**Comment by ghost** [comment] 2022-02-12 12:06
I can confirm the problem and it looks like the droplet code in install.php and upgrade.php is not working correctly

@webbird Is it possible that you can check it?

**Comment by webbird** [comment] 2022-02-14 09:14
This is strange. Importing a droplet should not change any module version.

`$module_directory` is defined in `info.php` which is `require`'d in both functions.

**Comment by webbird** [comment] 2022-02-14 09:42
The problem is located in `WB_PATH\modules\droplets\functions.inc.php` line 34.

`include realpath(dirname(__FILE__).'/info.php');`

This line includes the info.php of the droplets module, which sets $module_directory to "droplets". As $module_directory is global, this overwrites "news_img" with "droplets". This error will happen with any module that uses the functions.inc.php of the droplets module to install droplets.

**Comment by webbird** [comment] 2022-02-14 09:48
I've added a workaround to install.php and upgrade.php. (Untested.)

**Comment by ghost** [comment] 2022-02-27 21:23
In a first Test on my TE the Bugfix works.

@gchriz can you confirm this too

**Comment by gchriz** [comment] 2022-02-28 06:55
Since I currently don't have a test instance I needed to trick a bit (and learned more about those things under the hood!  ;-)).

Yes, the bugfix is working. The version numbers are/remain correct now. Thank you @webbird

**Comment by ghost** [comment] 2022-02-28 20:23
fixed with https://github.com/WBCE/News-with-Images/commit/67c5c90943503f1f1116d710a95464bd2d8e15d8 and https://github.com/WBCE/News-with-Images/commit/96ddae82767f1ebe7b1a59f1b9779747498f7ba6

**Closed as completed by ghost** 2022-02-28 20:23 UTC
Labels: bug
